#-------------------------------

#dataSource.driverClassName=org.postgresql.Driver
#dataSource.url=jdbc:postgresql://rds-postgresql-rss.cwdcd3pdjus7.us-east-1.rds.amazonaws.com:5432/datrixo
#dataSource.username=rds_sentimarket
#dataSource.password=Senti$1G

#hibernate.dialect=org.hibernate.dialect.PostgreSQL9Dialect
#validate update create create-drop
#hibernate.hbm2ddl.auto=validate

#------------------------------------

dataSource.driverClassName=org.hsqldb.jdbcDriver
dataSource.url=jdbc:hsqldb:mem:test
dataSource.username=sa
dataSource.password=

hibernate.dialect=org.hibernate.dialect.HSQLDialect
hibernate.hbm2ddl.auto=create

#-----------------------------------------



hibernate.show_sql=false
hibernate.format_sql=false
hibernate.use_sql_comments=false

#------------------
# An infura endpoint
web3j.client-address = https://ropsten.infura.io/v3/ffcb9542629345a4b433440eb2f0d573
web3j.admin-client = false


wallet.private-key=74C81447C076F03DD4350EC5272A47799401F55531DCED4A5560206E2DAC47DE
smart-contract.address=0x09C1A88e7a624833ec5C9D4bdb07B86678114ed8
