#-------------------------------

#dataSource.driverClassName=org.postgresql.Driver
#dataSource.url=jdbc:postgresql://rds-postgresql-rss.cwdcd3pdjus7.us-east-1.rds.amazonaws.com:5432/datrixo
#dataSource.username=rds_sentimarket
#dataSource.password=Senti$1G

#hibernate.dialect=org.hibernate.dialect.PostgreSQL9Dialect
#validate update create create-drop
#hibernate.hbm2ddl.auto=validate

#------------------------------------

#dataSource.driverClassName=org.hsqldb.jdbcDriver
#dataSource.url=jdbc:hsqldb:mem:test
#dataSource.username=sa
#dataSource.password=

#hibernate.dialect=org.hibernate.dialect.HSQLDialect
#hibernate.hbm2ddl.auto=create

#-----------------------------------------

#hibernate.show_sql=false
#hibernate.format_sql=false
#hibernate.use_sql_comments=false

#------------------
# An infura endpoint

# 0x6034852062eB6a478357F97C4B3C620115d7515B Datrixo_Test_1
# web3j.client-address = https://ropsten.infura.io/v3/ffcb9542629345a4b433440eb2f0d573
# web3j.admin-client = false

# wallet.private-key=74C81447C076F03DD4350EC5272A47799401F55531DCED4A5560206E2DAC47DE
# Ropsten old contract DRX
# smart-contract.address=0xed6B5a307Ff305F1C36a532B2E2ef7d0C9F143E9

# Ropsten NEW contract DRXT
# smart-contract.address=0x664DC963C77972a174eEc4C9b2574BcDc52F6Ad1

# MainNet
# LIVE DRXT contract owner
# 0x1214257a9F639C60dAAEA801af4c9b8360b6d516
web3j.client-address = https://mainnet.infura.io/v3/fa1ca08a82a34679aeb118281e6cecf8
web3j.admin-client = false
wallet.private-key=80A08D02D452776663D71BE17F06CDD64E038AEC5F9F4472028554A8B9BE78B2
smart-contract.address=0xe8e0487b4a76db81c524b4c3f4a5a34f9f49f6df

#--------------------------------------------
# Multi entity managers

# h2 --------------
h2.jdbc.driverClassName=org.h2.Driver
h2.jdbc.url=jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
h2.jdbc.user=sa
h2.jdbc.pass=

#http://localhost:8080/h2-console
spring.h2.console.enabled=false

h2.hibernate.hbm2ddl.auto=update
h2.hibernate.show_sql=false
#------------------

#mysql-------------
mysql.jdbc.driverClassName=com.mysql.jdbc.Driver

#mysql.jdbc.url=jdbc:mysql://localhost:3306/datrixo?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=EST5EDT
#mysql.jdbc.user=datrixo

# sentimarket7@gmail.com - production
mysql.jdbc.url=jdbc:mysql://datrixo-db.cwdcd3pdjus7.us-east-1.rds.amazonaws.com:3306/datrixo?useSSL=false&useUnicode=true&characterEncoding=UTF8

#adm.datrixo@gmail.com - not work
#mysql.jdbc.url=jdbc:mysql://datrixo-instance.cvyjbgmdjn77.us-east-2.rds.amazonaws.com:3306/datrixo?useSSL=false&useUnicode=true&characterEncoding=UTF8

mysql.jdbc.user=datrixo_master

mysql.jdbc.pass=Wp007adm

mysql.hibernate.hbm2ddl.auto=update
mysql.hibernate.show_sql=false
#-------------------

#postgresql-------------
#mysql.jdbc.driverClassName=org.postgresql.Driver
#mysql.jdbc.url=jdbc:postgresql://localhost:5432/datrixo
#mysql.jdbc.user=postgres

#mysql.jdbc.url=jdbc:mysql://datrixo-db.cwdcd3pdjus7.us-east-1.rds.amazonaws.com:3306/datrixo?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=EST5EDT
#mysql.jdbc.user=datrixo_master

#mysql.jdbc.pass=success1G

#mysql.hibernate.hbm2ddl.auto=update
#mysql.hibernate.show_sql=true
#-------------------
