#-------------------------------

#dataSource.driverClassName=org.postgresql.Driver
#dataSource.url=jdbc:postgresql://rds-postgresql-rss.cwdcd3pdjus7.us-east-1.rds.amazonaws.com:5432/datrixo
#dataSource.username=rds_sentimarket
#dataSource.password=Senti$1G

#hibernate.dialect=org.hibernate.dialect.PostgreSQL9Dialect
#validate update create create-drop
#hibernate.hbm2ddl.auto=validate

#------------------------------------

#dataSource.driverClassName=org.hsqldb.jdbcDriver
#dataSource.url=jdbc:hsqldb:mem:test
#dataSource.username=sa
#dataSource.password=

#hibernate.dialect=org.hibernate.dialect.HSQLDialect
#hibernate.hbm2ddl.auto=create

#-----------------------------------------

#hibernate.show_sql=false
#hibernate.format_sql=false
#hibernate.use_sql_comments=false

#------------------
# An infura endpoint

web3j.client-address = https://ropsten.infura.io/v3/ffcb9542629345a4b433440eb2f0d573
web3j.admin-client = false

wallet.private-key=74C81447C076F03DD4350EC5272A47799401F55531DCED4A5560206E2DAC47DE
smart-contract.address=0xed6B5a307Ff305F1C36a532B2E2ef7d0C9F143E9

#--------------------------------------------
# Multi entity managers

# h2 --------------
h2.jdbc.driverClassName=org.h2.Driver
h2.jdbc.url=jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
h2.jdbc.user=sa
h2.jdbc.pass=

#http://localhost:8080/h2-console
spring.h2.console.enabled=true

h2.hibernate.hbm2ddl.auto=update
h2.hibernate.show_sql=true
#------------------

#mysql-------------
mysql.jdbc.driverClassName=com.mysql.jdbc.Driver
#mysql.jdbc.url=jdbc:mysql://localhost:3306/datrixo?useSSL=false&useUnicode=true&characterEncoding=UTF8
#mysql.jdbc.user=datrixo

mysql.jdbc.url=jdbc:mysql://datrixo-db.cwdcd3pdjus7.us-east-1.rds.amazonaws.com:3306/datrixo?useSSL=false&useUnicode=true&characterEncoding=UTF8
mysql.jdbc.user=datrixo_master

mysql.jdbc.pass=Wp007adm

mysql.hibernate.hbm2ddl.auto=update
mysql.hibernate.show_sql=true
#-------------------
