<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.datrixo</groupId>
        <artifactId>crypto-datrixo-site</artifactId>
        <version>1.0</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.datrixo</groupId>
    <artifactId>ico-page-site</artifactId>
    <packaging>war</packaging>

    <properties>
        <start-class>com.datrixo.crypto_datrixo_site.ico_page.App</start-class>
        <maven.build.timestamp.format>yyyyMMddHHmmss</maven.build.timestamp.format>
        <beanstalk.versionLabel>${maven.build.timestamp}</beanstalk.versionLabel>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>

        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
        </dependency>

        <!--<dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <version>9.4.1207</version>
        </dependency>-->
        <!-- https://mvnrepository.com/artifact/mysql/mysql-connector-java -->

        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>8.0.16</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.web3j</groupId>
            <artifactId>web3j-spring-boot-starter</artifactId>
            <version>4.0.3</version>
        </dependency>

        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
            <version>2.6</version>
        </dependency>

    </dependencies>

    <repositories>
        <repository>
            <id>java-net-repo</id>
            <url>https://maven.java.net/content/repositories/public/</url>
        </repository>
    </repositories>

    <build>
        <finalName>ico-page-site</finalName>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
            <!--<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-war-plugin</artifactId>
                <version>2.6</version>
                <configuration>
                    <webResources>
                        <resource>
                            <directory>${basedir}/frontend-ico-page/dist/frontend-ico-page</directory>
                            <targetPath>/WEB-INF/classes/static/</targetPath>
                            <includes>
                                <include>**</include>
                            </includes>
                        </resource>
                        <resource>
                            <directory>${basedir}/frontend-investor-page/dist</directory>
                            <targetPath>/WEB-INF/classes/static/investor-page/</targetPath>
                            <includes>
                                <include>**</include>
                            </includes>
                        </resource>
                    </webResources>
                    <failOnMissingWebXml>false</failOnMissingWebXml>
                </configuration>
            </plugin>-->
        </plugins>
    </build>

    <!--<profiles>

        <profile>
            <id>deploy-on-aws</id>
            <build>
                <plugins>
                    &lt;!&ndash;deploy to amazon elastic beanstalk&ndash;&gt;
                    <plugin>
                        <artifactId>maven-deploy-plugin</artifactId>
                        <configuration>
                            <skip>true</skip>
                        </configuration>
                    </plugin>
                    &lt;!&ndash;deploy on AWS beanstalk config crypto-datrixo-site&ndash;&gt;
                    <plugin>
                        <groupId>br.com.ingenieux</groupId>
                        <artifactId>beanstalk-maven-plugin</artifactId>
                        <version>1.5.0</version>
                        <executions>
                            <execution>
                                <id>deploy</id>
                                <phase>deploy</phase>
                                <goals>
                                    <goal>upload-source-bundle</goal>
                                    <goal>create-application-version</goal>
                                    <goal>update-environment</goal>
                                </goals>
                            </execution>
                        </executions>
                        &lt;!&ndash;ico-page&ndash;&gt;
                        <configuration>
                            <applicationName>crypto-datrixo-site</applicationName>
                            <environmentName>ico-page-site</environmentName>
                            <regionName>us-east-1</regionName>
                            <cnamePrefix>ico-page-site</cnamePrefix>
                            <serverId>senti@aws.amazon.com</serverId>
                            <verbose>true</verbose>
                            <s3Bucket>elasticbeanstalk-us-east-1-508213701893</s3Bucket>
                            <versionLabel>${project.build.finalName}.${maven.build.timestamp}</versionLabel>
                            <versionDescription>Deployed from maven</versionDescription>
                            <s3Key>${project.build.finalName}.${maven.build.timestamp}.jar</s3Key>
                            <environmentRef>ico-page-site</environmentRef>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>

    </profiles>-->

</project>
